name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: linux_amd64
          - goos: darwin
            goarch: amd64
            suffix: darwin_amd64
          - goos: darwin
            goarch: arm64
            suffix: darwin_arm64
          - goos: windows
            goarch: amd64
            suffix: windows_amd64
            extension: .exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Get dependencies
      run: go mod download

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        mkdir -p dist
        go build -ldflags="-s -w" -o dist/easy-cli${{ matrix.extension }} .

    - name: Create tarball
      run: |
        cd dist
        tar -czf easy-cli_${{ matrix.suffix }}.tar.gz easy-cli${{ matrix.extension }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: easy-cli-${{ matrix.suffix }}
        path: dist/easy-cli_${{ matrix.suffix }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist/
        merge-multiple: true

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.tar.gz
        body: |
          ## Changes
          
          See [CHANGELOG.md](CHANGELOG.md) for details.
          
          ## Installation
          
          ### One-line Install (Recommended)
          ```bash
          curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | bash
          ```
          
          ### Manual Installation
          1. Download the appropriate tarball for your platform
          2. Extract: `tar -xzf easy-cli_*.tar.gz`
          3. Make executable: `chmod +x easy-cli`
          4. Move to PATH: `sudo mv easy-cli /usr/local/bin/`
        draft: false
        prerelease: false